#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload
    fi
fi

if [ "$1" = "purge" ]; then
    rm -rf /var/lib/home-fern
    rm -rf /etc/home-fern

    if id "home-fern" >/dev/null 2>&1; then
        userdel home-fern
    fi

    if getent group home-fern >/dev/null 2>&1; then
        groupdel home-fern
    fi
fi

exit 0
