name: Build and Release
on:
  push:
    tags: [ "v*" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: GitHub Actions environment variables
        run: printenv | sort

      - name: Clone
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        id: build
        run: |
          make
          echo "Checking for build artifact..."
          ls -lah home-fern*         

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        id: docker_build
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')

          echo "Building image: $IMAGE_TAG"
          docker buildx build --tag $IMAGE_TAG .
          
          # Set the image tag as an output
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Push Docker image to Container Registry
        run: docker push ${{ steps.docker_build.outputs.image_tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Release based on tag ${{ github.ref_name }}.
            Docker Image: `${{ steps.docker_build.outputs.image_tag }}`
          files: |
            release/*
